#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# COMPONENT: main

verilator --cc --exe --Mdir HLS_output//verilator_beh/verilator_obj -Wno-fatal -Wno-lint -sv -O3 top.sv top.v HLS_output//simulation/testbench_main_main.cpp HLS_output//simulation/testbench_main_tb.v --top-module main_tb
if [ $? -ne 0 ]; then
   exit 1;
fi


ln -s ../../../HLS_output/ HLS_output//verilator_beh/verilator_obj
make -C HLS_output//verilator_beh/verilator_obj -j4 OPT_FAST="-O1 -fstrict-aliasing" -f Vmain_tb.mk Vmain_tb

HLS_output//verilator_beh/verilator_obj/Vmain_tb 2>&1 | tee HLS_output//verilator_beh/main_verilator.log


